{
 "title": "EFM Agent Class",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "agentClass", "label": "Agent Class", "query": { "query": "label_values(agentClass)" } },
   { "name": "agentTimeout", "label": "Agent Timeout (sec)", "query": "60" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Agent Manifests",
   "type": "stat",
   "description": "Number of agent manifests seen in the currently selected time interval",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(time() - max(efm_heartbeat_lastSeenTime_seconds{agentClass=~\"$agentClass\"}) by (agentManifestId) < ${agentTimeout})"
    }
   ]
  },
  {
   "title": "Number of Online Agents",
   "type": "stat",
   "description": "Number of agents seen in the currently selected time interval",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(time() - max(efm_heartbeat_lastSeenTime_seconds{agentClass=~\"$agentClass\"}) by (agentId) < ${agentTimeout})"
    }
   ]
  },
  {
   "title": "Total Number of Agents",
   "type": "stat",
   "description": "Number of agents seen in the currently selected time interval",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(efm_heartbeat_lastSeenTime_seconds{agentClass=~\"$agentClass\"}) by (agentId))"
    }
   ]
  },
  {
   "title": "Agent Statistics",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(time() - max(efm_heartbeat_lastSeenTime_seconds{agentClass=~\"$agentClass\"}) by (agentId) < ${agentTimeout})",
     "legendFormat": "Online Agents"
    },
    {
     "expr": "count(max(efm_heartbeat_lastSeenTime_seconds{agentClass=~\"$agentClass\"}) by (agentId))",
     "legendFormat": "Total Number Of Agents"
    }
   ]
  },
  { "title": "Heartbeats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Heartbeats per Minute by Agent Class",
   "type": "graph",
   "description": "Heartbeats per Minute (hpm) aggregated by agent class",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(efm_heartbeat_count_total{agentClass=~\"$agentClass\",agentManifestId=\"\"}[1m])*60) by (agentClass)",
     "legendFormat": "{{agentClass}}  - Light Heartbeat"
    },
    {
     "expr": "sum(rate(efm_heartbeat_count_total{agentClass=~\"$agentClass\",agentManifestId!=\"\"}[1m])*60) by (agentClass)",
     "legendFormat": "{{agentClass}}  - Full Heartbeat"
    }
   ]
  },
  {
   "title": "Avg Heartbeats per Minute",
   "type": "stat",
   "description": "Average number of heartbeats per minute (hpm) by agent class, over the last 5 minutes",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(sum(rate(efm_heartbeat_count_total{agentClass=~\"$agentClass\"}[1m])*60) by (agentClass))"
    }
   ]
  },
  {
   "title": "Average Heartbeat Content Length by Agent Class",
   "type": "timeseries",
   "description": "Average content length of heartbeats by each agent class",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg((efm_heartbeat_contentLength_sum{agentClass=~\"$agentClass\", agentManifestId=\"\"}/efm_heartbeat_contentLength_count{agentClass=~\"$agentClass\", agentManifestId=\"\"})) by (agentClass)",
     "legendFormat": "{{agentClass}} - Light Heartbeat"
    },
    {
     "expr": "avg((efm_heartbeat_contentLength_sum{agentClass=~\"$agentClass\", agentManifestId!=\"\"}/efm_heartbeat_contentLength_count{agentClass=~\"$agentClass\", agentManifestId!=\"\"})) by (agentClass)",
     "legendFormat": "{{agentClass}} - Full Heartbeat"
    }
   ]
  },
  {
   "title": "Heartbeat Data Rate",
   "type": "stat",
   "description": "Total data rate of all heartbeat data for the selected agent class(es)",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(efm_heartbeat_contentLength_sum{agentClass=~\"$agentClass\"}[$__range]))"
    }
   ]
  }
 ]
}