{
 "title": "EFM",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "agent_timeout_s", "label": "Agent Timeout (sec)", "query": "60" }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(efm_http_server_requests_seconds) by (instance))"
    }
   ]
  },
  {
   "title": "AgentClass Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(efm_repo_AgentClassRepository_size)"
    }
   ]
  },
  {
   "title": "AgentManifest Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(efm_repo_AgentManifestRepository_size)"
    }
   ]
  },
  {
   "title": "Heartbeat Data Rate",
   "type": "stat",
   "gridPos": { "h": 12, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(efm_heartbeat_contentLength_sum[$__range]))"
    }
   ]
  },
  {
   "title": "Active vs Missing Agents in time range",
   "type": "piechart",
   "description": "Collects the activity and inactivity of agents in the given time range doesn't deal with anything happening outside it",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(time() - (max(efm_heartbeat_lastSeenTime_seconds) by (agentId)) < $agent_timeout_s)",
     "legendFormat": "Active"
    },
    {
     "expr": "count((time() - (max(efm_heartbeat_lastSeenTime_seconds) by (agentId))) > $agent_timeout_s < $__range_s)",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Agent Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(efm_repo_AgentRepository_size)"
    }
   ]
  },
  {
   "title": "Flow Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(efm_repo_FlowRepository_size)"
    }
   ]
  },
  {
   "title": "Operation Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(efm_repo_OperationRepository_size)"
    }
   ]
  },
  { "title": "EFM Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Heartbeat TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(efm_http_server_requests_seconds_count{uri=~\"(/efm)?/api/c2-protocol/heartbeat\"}[1m]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Acknowledge TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(efm_http_server_requests_seconds_count{uri=~\"(/efm)?/api/c2-protocol/acknowledge\"}[1m]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Heartbeat Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(efm_http_server_requests_seconds{uri=~\"(/efm)?/api/c2-protocol/heartbeat\", status!~\"[4|5]..\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Acknowledge Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(efm_http_server_requests_seconds{uri=~\"(/efm)?/api/c2-protocol/acknowledge\", status!~\"[4|5]..\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Heartbeat non success distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(increase(efm_http_server_requests_seconds_count{uri=~\"(/efm)?/api/c2-protocol/heartbeat\", status!~\"[2|3]..\"}[$__range])))",
     "legendFormat": "Status: {{status}}"
    }
   ]
  },
  {
   "title": "Acknowledge non success distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(increase(efm_http_server_requests_seconds_count{uri=~\"(/efm)?/api/c2-protocol/acknowledge\", status!~\"[2|3]..\"}[$__range])))",
     "legendFormat": "Status: {{status}}"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Kafka TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(efm_spring_kafka_template_seconds_count{}[1m]))",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Kafka Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(efm_spring_kafka_template_seconds{result=\"success\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Kafka Success vs Failure Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(efm_spring_kafka_template_seconds_count{result=\"success\"}[1m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(efm_spring_kafka_template_seconds_count{result=\"failure\"}[1m]))",
     "legendFormat": "Failure"
    }
   ]
  },
  { "title": "Hazelcast", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Hazelcast Statistics",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(efm_cache_size) by (cache)", "legendFormat": "{{cache}}" }
   ]
  }
 ]
}